version: "3"
services:
  web:
    build:
      context: ./fastapi_app
    environment:
      - RABBITMQ_HOST=rabbitmq
      - REDIS_HOST=redis
      - RESULTS_DIR=/data/results
      - RESOURCES_DIR=/data/resources
    ports:
      - "5001:5001"
    depends_on:
      - redis
      - rabbitmq
    volumes:
      - ./data:/data
    networks:
      - sim_network

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
    networks:
      - sim_network

  redis:
    image: redis:7
    networks:
      - sim_network

  example_worker:
    build:
      context: ./task_queue
    environment:
      - RABBITMQ_HOST=rabbitmq
      - REDIS_HOST=redis
      - RESULTS_DIR=/data/results
      - RESOURCES_DIR=/data/resources
    depends_on:
      - redis
      - rabbitmq
    volumes:
      - ./data:/data
    networks:
      - sim_network

  mosaik-orbit:
    build:
      context: ./mosaik/mosaik-gui
      dockerfile: docker/Dockerfile.mosaik-orbit
    ports:
      - "8442:8442"
    networks:
      sim_network:
        aliases:
          - backend

  mosaik-gui:
    build:
      context: ./mosaik/mosaik-gui
      dockerfile: docker/Dockerfile.mosaik-gui
      args:
        VITE_WS_URL: ws://mosaik-gui/ws
    ports:
      - "8002:80"
    depends_on:
      - mosaik-orbit
    networks:
      - sim_network

  mosaik-worker:
    build:
      context: .
      dockerfile: mosaik/mosaik-worker/Dockerfile
    environment:
      - RABBITMQ_HOST=rabbitmq
      - REDIS_HOST=redis
      - MOSAIK_WS_URL=ws://mosaik-orbit:8442
      - RESULTS_DIR=/data/results
      - RESOURCES_DIR=/data/resources
    depends_on:
      - redis
      - rabbitmq
      - mosaik-orbit
    volumes:
      - ./data:/data
    networks:
      - sim_network

networks:
  sim_network:
